import mongoose from "mongoose";

const messageSchema = new mongoose.Schema(
	{
		senderId: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "User",
			required: true,
		},

		recevierId: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "User",
			required: true,
		},

		// ID generated by the client.
		// Used to prevent duplicate messages when a request is retried.
		clientMessageId: {
			type: String,
			required: true,
		},

		text: {
			type: String,
			trim: true,
			maxlength: 2000,
		},

		image: {
			type: String,
		},

		status: {
			type: String,
			enum: ["sent", "delivered", "read"],
			default: "sent",
		},

		deliveredAt: {
			type: Date,
			default: null,
		},

		readAt: {
			type: Date,
			default: null,
		},
		isDeleted: {
			type: Boolean,
			default: false,
		},

		deletedAt: {
			type: Date,
			default: null,
		},
	},
	{
		timestamps: true,
	}
);

// A sender cannot create two messages with the same clientMessageId.
messageSchema.index(
	{ senderId: 1, clientMessageId: 1 },
	{ unique: true }
);

// This will become very useful when we implement pagination.
messageSchema.index({
	senderId: 1,
	recevierId: 1,
	createdAt: -1,
});

messageSchema.index({
	recevierId: 1,
	senderId: 1,
	createdAt: -1,
});

const Message = mongoose.model("Message", messageSchema);

export default Message;